### ISSUE TITLE
Cannot read properties of undefined (reading 'click')

### ISSUE THREAD

**Issue by RalucaEM** [evmer/scribd-downloader#9]
Traceback (most recent call last):
  File "C:\Users\raluc\Downloads\scribd-downloader-main\run.py", line 132, in <module>
    page.evaluate("() => document.querySelectorAll('button.load_next_btn')[0].click()")
  File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\sync_api\_generated.py", line 8622, in evaluate
    self._sync(
  File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
  File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 411, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 277, in evaluate
    await self._channel.send(
  File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: TypeError: Cannot read properties of undefined (reading 'click')
    at eval (eval at evaluate (:195:30), <anonymous>:1:59)
    at UtilityScript.evaluate (<anonymous>:202:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

**Comment by catfordfire** [comment]
I'm also getting this error.

**Comment by catfordfire** [comment]
> Traceback (most recent call last): File "C:\Users\raluc\Downloads\scribd-downloader-main\run.py", line 132, in page.evaluate("() => document.querySelectorAll('button.load_next_btn')[0].click()") File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\sync_api_generated.py", line 8622, in evaluate self._sync( File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright_impl_sync_base.py", line 104, in _sync return task.result() File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright_impl_page.py", line 411, in evaluate return await self._main_frame.evaluate(expression, arg) File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright_impl_frame.py", line 277, in evaluate await self._channel.send( File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright_impl_connection.py", line 61, in send return await self._connection.wrap_api_call( File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright_impl_connection.py", line 461, in wrap_api_call return await cb() File "C:\Users\raluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright_impl_connection.py", line 96, in inner_send result = next(iter(done)).result() playwright._impl._api_types.Error: TypeError: Cannot read properties of undefined (reading 'click') at eval (eval at evaluate (:195:30), :1:59) at UtilityScript.evaluate (:202:19) at UtilityScript. (:1:44)

try deleting the session.json file and logging in with a working account. Scribd have been throttling accounts, so this is likely to be the problem. I did this and it's working fine again. I think I was logged in with an expired account, so when I cleared the json file and logged in again, all was well.
